var SCReporting = {
	'metacontent': '',
	'metaroot': 'acs::web::',
	'pagepath': (location.pathname) ? location.pathname : '',
	'pagetitle': (document.title) ? document.title : '',
	'subdir': '',
	'title': '',
	'map': {},
	
	'init': function() {
		this.setSubdir();
		this.normalizeTitle();
		this.mapPage();
		this.insertMetaTag();
	},
	'insertMetaTag': function() {
		var head = document.getElementsByTagName('head').item(0);
		var meta = document.createElement('meta');
		meta.setAttribute('name', 'omni_page');
		meta.setAttribute('content', this.metaroot + this.metacontent);
		head.appendChild(meta);
	},
	'mapPage': function() {
		if (this.subdir == '') {
			this.metacontent = 'homepage';
		}
		else if (this.map.psp[this.subdir]) {
			this.metacontent = 'psp::' + this.map.psp[this.subdir] + '::' + this.title;
		}
		else if (this.map.ta[this.subdir]) {
			this.metacontent = 'ta::' + this.map.ta[this.subdir] + '::' + this.title;
		}
		else if (this.map.faq[this.subdir]) {
			this.metacontent = 'faq::' + this.map.faq[this.subdir] + '::' + this.title;
		}
		else if (this.map.qp[this.subdir]) {
			this.metacontent = 'qp::' + this.map.qp[this.subdir] + '::' + this.title;
		}
		else if (this.map.price[this.subdir]) {
			this.metacontent = 'price::' + this.map.price[this.subdir] + '::' + this.title;
		}
		else if (this.map.survey[this.subdir]) {
			this.metacontent = 'survey::' + this.map.survey[this.subdir] + '::' + this.title;
		}
		else if (this.map.tsp[this.subdir]) {
			this.metacontent = 'tsp::' + this.map.tsp[this.subdir] + '::' + this.title;
		}
		else {
			this.metacontent = this.title;
		}
	},
	'normalizeTitle': function() {
		this.title = this.pagetitle;
		this.title = this.title.replace(/\&mdash;/g, '-');
		this.title = this.title.replace(/\&ndash;/g, '-');
		this.title = this.title.replace(/\Ñ/g, '-');
		this.title = this.title.replace(/\Ð/g, '-');
		this.title = this.title.replace(/\&nbsp;/g, ' ');
		this.title = this.title.replace(/\s+/g, ' ');
		this.title = this.title.replace(/\"/g, '\'');
		this.title = this.title.split(' - ');
		if (this.title.length > 2) {
			this.title.shift();  /* Remove 'Apple' */
			this.title.shift();  /* Remove 'Support' */
			this.title = this.title.join(' - ');
		}
		else {
			this.title = this.title.toString();
		}
		this.title = this.title.replace(/^\s+(.+)/, '$1');
		this.title = this.title.replace(/(.+)\s+$/, '$1');
	},
	'setSubdir': function() {
		if (this.pagepath.indexOf('/support/') != -1) {
			this.subdir = this.pagepath.match(/\/support\/(.*)$/)[1];
			this.subdir = this.subdir.replace(/(.+)(\/|\/index\.html)$/, '$1');
			this.subdir = this.subdir.replace(/^index\.html$/, '');
		}
		else {
			this.subdir = 'undefined';
		}
	},
	'trackClick': function(subtitle, url, hyphenate, showMetaContent) {
		if (typeof(s_gi) != 'undefined' && subtitle != undefined) {
			var s = s_gi(s_account);
			var orig_pagename = s.pageName;
			var lastparens = orig_pagename.match(/\([^\(\)]+\)$/);
			var country = (lastparens != null && lastparens.length > 0) ? ' ' + lastparens[0] : '';
			var meta_content = (showMetaContent == undefined || showMetaContent == true) ? this.metacontent : '';
			var hyphen = (hyphenate == undefined || hyphenate == true) ? ' - ' : '';
			s.pageName = this.metaroot + meta_content + hyphen + subtitle + country;
			s.prop4 = (url != undefined) ? url : document.URL;
			s.prop6 = s.getQueryParam('cp') + ": " + this.metaroot + meta_content + subtitle + country;
			void(s.t());
		}
	}
};

SCReporting.map = {

	"psp": {
		"airport": "airport",
		"aperture": "aperture",
		"applecare": "applecare",
		"applecare/welcome": "applecare::welcome",
		"applecare/register": "applecare::register",
		"applecare/view": "applecare::view",
		"applecare/purchase": "applecare::purchase",
		"applecare/manage": "applecare::manage",
		"applecare/resources": "applecare::resources",
		"applecare/contact": "applecare::contact",
		"applecare/ww": "applecare::worldwide",
		"appletv": "appletv",
		"appletv/getstarted": "appletv::get started",
		"appletv/basics": "appletv::basics",
		"appletv/wifi": "appletv:;wifi + networking",
		"appletv/homesharing": "appletv::home sharing",
		"appletv/remote": "appletv::remote",
		"appletv/troubleshooting": "appletv::troubleshooting",
		"appletv/service": "appletv::hardware service",
		"appletv/service/faq": "appletv::service faq",
		"appletv/contact": "appletv::contact support",
		"appletv/1st_generation": "appletv::1st generation",
		"bluetooth": "bluetooth",
		"bonjour": "bonjour",
		"bootcamp": "boot camp",
		"color": "color",
		"compressor": "compressor",
		"displays": "displays",
		"displays/cables": "displays::cables, ports, and adapters",
		"displays/contact": "displays::contact support",
		"displays/downloads": "displays::recent software updates",
		"displays/getstarted": "displays::get started",
		"displays/topics": "displays::featured topics",
		"dvdstudiopro": "dvd studio pro",
		"emac": "emac",
		"finalcutexpress": "final cut express",
		"finalcutpro": "final cut pro",
		"finalcutserver": "final cut server",
		"finalcutstudio": "final cut studio",
		"garageband": "garageband",
		"hardware": "hardware",
		"headset": "headset",
		"ibook": "ibook",
		"ibooksauthor": "ibooks author",
		"ibooksauthor/getstarted": "ibooks author::get started",
		"ibooksauthor/media": "ibooks author::media",
		"ibooksauthor/publishing": "ibooks author::publishing",
		"ibooksauthor/tips": "ibooks author::tips",
		"ibooksauthor/contact": "ibooks author::contact",
		"ical": "ical",
		"ichat": "ichat",
		"icloud": "icloud",
		"icloud/getstarted": "icloud::get started",
		"icloud/account": "icloud::account",
		"icloud/backup": "icloud::backup",
		"icloud/back-to-my-mac": "icloud::back to my mac",
		"icloud/bookmarks": "icloud::bookmarks",
		"icloud/calendar": "icloud::calendar & reminders",
		"icloud/contacts": "icloud::contacts",
		"icloud/documents": "icloud::documents in the cloud",
		"icloud/find-my-friends": "icloud::find my friends",
		"icloud/find-my-device": "icloud::find my device",
		"icloud/itunes": "icloud::itunes in the cloud",
		"icloud/mail-notes": "icloud::mail & notes",
		"icloud/photo-stream": "icloud::photo stream",
		"icloud/storage": "icloud::storage upgrades",
		"icloud/systemstatus": "icloud::system status",
		"icloud/contact": "icloud::contact support",
		"idvd": "idvd",
		"ilife": "ilife",
		"imac/g3": "imac g3",
		"imac/g4": "imac g4",
		"imac/g5": "imac g5",
		"imac/intel": "intel-based imac",
		"imac/intel/accessories": "intel-based imac::accessories",
		"imac/intel/applications": "intel-based imac::applications",
		"imac/intel/windowsmac": "intel-based imac::windows on a mac",
		"imac/intel/contact": "intel-based imac::contact support",
		"imac/intel/downloads": "intel-based imac::recent software updates",
		"imac/intel/mail": "intel-based imac::mail",
		"imac/intel/migration": "intel-based imac::moving files to a new mac",
		"imac/intel/new_user": "intel-based imac::new to mac",
		"imac/intel/topics": "intel-based imac::featured topics",
		"imac/intel/wifi": "intel-based imac::wi-fi",
		"ios/apps": "ios apps",
		"ios/contact": "ios apps::contact",
		"ios/garageband": "ios apps::garageband",
		"ios/ibooks": "ios apps::ibooks",
		"ios/imovie": "ios apps::imovie",
		"ios/iphoto": "ios apps::iphoto",
		"ios/itunes-u": "ios apps::itunes u",
		"ios/keynote": "ios apps::keynote",
		"ios/numbers": "ios apps::numbers",
		"ios/other": "ios apps::other apps",
		"ios/pages": "ios apps::pages",
		"ios/podcasts": "ios apps::podcasts",
		"ipad": "ipad",
		"ipad/3g": "ipad::3g",
		"ipad/accessories": "ipad::accessories",
		"ipad/applications": "ipad::applications",
		"ipad/basics": "ipad::basics",
		"ipad/contact": "ipad::contact",
		"ipad/enterprise": "ipad::enterprise",
		"ipad/facetime": "ipad::facetime",
		"ipad/getstarted": "ipad::get started",
		"ipad/mail": "ipad::mail",
		"ipad/service": "ipad::service",
		"ipad/syncing": "ipad::syncing",
		"ipad/wifi": "ipad::wifi",
		"iphone": "iphone",
		"iphone/accessories": "iphone::accessories",
		"iphone/applications": "iphone::applications",
		"iphone/basics": "iphone::basics",
		"iphone/contact": "iphone::contact",
		"iphone/enterprise": "iphone::enterprise",
		"iphone/facetime": "iphone::facetime",
		"iphone/getstarted": "iphone::get started",
		"iphone/ibooks": "iphone::ibooks",
		"iphone/imovie": "iphone::imovie",
		"iphone/mail": "iphone::mail",
		"iphone/phone": "iphone::phone",
		"iphone/service": "iphone::service",
		"iphone/syncing": "iphone::syncing",
		"iphone/wifi": "iphone::wifi",
		"iphone/chit": "ch-it::iphone",
		"iphone/chit/accessories": "ch-it::iphone::accessories",
		"iphone/chit/applications": "ch-it::iphone::applications",
		"iphone/chit/assistant": "ch-it::iphone::assistant",
		"iphone/chit/basics": "ch-it::iphone::basics",
		"iphone/chit/contact": "ch-it::iphone::contact",
		"iphone/chit/enterprise": "ch-it::iphone::enterprise",
		"iphone/chit/facetime": "ch-it::iphone::facetime",
		"iphone/chit/getstarted": "ch-it::iphone::get started",
		"iphone/chit/ibooks": "ch-it::iphone::ibooks::redirect",
		"iphone/chit/imovie": "ch-it::iphone::imovie::redirect",
		"iphone/chit/mail": "ch-it::iphone::mail",
		"iphone/chit/phone": "ch-it::iphone::phone",
		"iphone/chit/service": "ch-it::iphone::service",
		"iphone/chit/syncing": "ch-it::iphone::syncing",
		"iphone/chit/wifi": "ch-it::iphone::wifi",
		"iphoto": "iphoto",
		"ipod/earlier": "ipod::ipod earlier",
		"ipodclassic": "ipod::ipod classic",
		"ipodhifi": "ipod accessories::ipod hi-fi",
		"ipodmini": "ipod::ipod mini",
		"ipodnano": "ipod::ipod nano",
		"ipodnano/contact": "ipodnano::contact",
		"ipodnano/getstarted": "ipodnano::get started",
		"ipodnano/how-to": "ipodnano::how to",
		"ipodnano/service": "ipodnano::service",
		"ipodnano/syncing": "ipodnano::syncing",
		"ipodnano/troubleshooting": "ipodnano::troubleshooting",
		"ipodnano/4th_5th_generation": "ipod::ipod nano 4th and 5th gen",
		"ipodnano/3rd_generation": "ipod::ipod nano 3rd gen",
		"ipodnano/earlier": "ipod::ipod nano earlier",
		"ipodshuffle": "ipod::ipod shuffle",
		"ipodshuffle/contact": "ipodshuffle::contact",
		"ipodshuffle/getstarted": "ipodshuffle::get started",
		"ipodshuffle/how-to": "ipodshuffle::how to",
		"ipodshuffle/service": "ipodshuffle::service",
		"ipodshuffle/syncing": "ipodshuffle::syncing",
		"ipodshuffle/troubleshooting": "ipodshuffle::troubleshooting",
		"ipodshuffle/3rd_generation": "ipod::ipod shuffle 3rd gen",
		"ipodshuffle/earlier": "ipod::ipod shuffle earlier",
		"ipodtouch": "ipod::ipod touch",
		"ipodtouch/accessories": "ipodtouch::accessories",
		"ipodtouch/applications": "ipodtouch::applications",
		"ipodtouch/basics": "ipodtouch::basics",
		"ipodtouch/contact": "ipodtouch::contact",
		"ipodtouch/facetime": "ipodtouch::facetime",
		"ipodtouch/getstarted": "ipodtouch::get started",
		"ipodtouch/ibooks": "ipodtouch::ibooks",
		"ipodtouch/imovie": "ipodtouch::imovie",
		"ipodtouch/mail": "ipodtouch::mail",
		"ipodtouch/service": "ipodtouch::service",
		"ipodtouch/syncing": "ipodtouch::syncing",
		"ipodtouch/wifi": "ipodtouch::wifi",
		"isight": "isight",
		"isync": "isync",
		"itunes": "itunes",
		"itunes/getstarted": "itunes::get started",
		"itunes/install": "itunes::install and update",
		"itunes/media": "itunes::move your media",
		"itunes/library": "itunes::manage and share your library",
		"itunes/in-the-cloud": "itunes::itunes in the cloud",
		"itunes/purchases": "itunes::purchases and downloads",
		"itunes/account": "itunes::account and billing",
		"itunes/cards-codes": "itunes::itunes cards and codes",
		"itunes/authorization": "itunes::authorize your computer",
		"itunes/troubleshooting": "itunes::itunes troubleshooting",
		"itunes/devices": "itunes::devices",
		"itunes/music": "itunes::music",
		"itunes/movies": "itunes::movies and tv",
		"itunes/apps": "itunes::apps",
		"itunes/books": "itunes::books",
		"itunes/itunes-u": "itunes::itunes u and podcasts",
		"itunes/contact": "itunes::contact support",
		"itunes/store": "itunes::itunes store",
		"itunes/vpp": "itunes::volume purchase program",
		"itunes-u": "itunes-u",
		"itunes-u/using": "itunes-u::using itunes-u",
		"itunes-u/course-manager": "itunes-u::course manager",
		"itunes-u/public-site-manager": "itunes-u::public site manager",
		"iweb": "iweb",
		"iwork": "iwork",
		"iworkcom": "iwork.com",
		"jaguar": "jaguar",
		"keyboard": "keyboard",
		"keynote": "keynote",
		"leopard/accounts": "mac os x 10.5::accounts",
		"leopard/addressbook": "mac os x 10.5::address book",
		"leopard": "mac os x 10.5",
		"leopard/install": "mac os x 10.5::install",
		"leopard/internet": "mac os x 10.5::internet",
		"leopard/mail": "mac os x 10.5::mail",
		"leopard/printing": "mac os x 10.5::printing",
		"leopard/sharing": "mac os x 10.5::sharing",
		"leopard/thirdparty": "mac os x 10.5::thirdparty",
		"leopard/timemachine": "mac os x 10.5::time machine",
		"latino/itunes": "itunes::latino itunes",
		"lion": "lion",
		"lion/applications": "lion::applications",
		"lion/basics": "lion::basics",
		"lion/contact": "lion::contact",
		"lion/howto": "lion::howto",
		"lion/installrecovery": "lion::installation and recovery",
		"lion/internetnetworking": "lion::internet and networking",
		"lion/mail": "lion::mail",
		"lion/printingscanning": "lion::printing and scanning",
		"lion/safari": "lion::safari",
		"lion/security": "lion::security",
		"lion/troubleshooting": "lion::troubleshooting",
		"lionserver": "lion server",
		"lionserver/advancedtopics": "lion server::advanced topics",
		"lionserver/clientmanagement": "lion server::client management",
		"lionserver/collaboration": "lion server::collaboration",
		"lionserver/contact": "lion server::contact",
		"lionserver/directoryservices": "lion server::directory services",
		"lionserver/filesharing": "lion server::file sharing",
		"lionserver/otherservices": "lion server::other services",
		"lionserver/podcast": "lion server::podcast",
		"lionserver/profilemanager": "lion server::profile manager",
		"lionserver/setupadministration": "lion server::setup and administration",
		"lionserver/systemimaging": "lion server::system imaging",
		"livetype": "livetype",
		"logicexpress": "logic express 8",
		"logicpro": "logic pro 8",
		"logicstudio": "logic studio",
		"mac/app-store": "mac app store",
		"mac/app-store/getstarted": "mac app store::get started",
		"mac/app-store/troubleshooting": "mac app store::troubleshooting",
		"mac/app-store/applications": "mac app store::applications",
		"mac/app-store/contact.html": "mac app store::contact support",
		"mac/facetime": "mac facetime",
		"mac/facetime/getstarted": "mac facetime::get started",
		"mac/facetime/troubleshooting": "mac facetime::troubleshooting",
		"mac/facetime/contact": "mac facetime::contact support",
		"macbook": "macbook",
		"macbook/accessories": "macbook::accessories",
		"macbook/applications": "macbook::applications",
		"macbook/batteries_power": "macbook::batteries and power",
		"macbook/bootcamp": "macbook::boot camp",
		"macbook/contact": "macbook::contact",
		"macbook/downloads": "macbook::downloads",
		"macbook/mail": "macbook::mail",
		"macbook/migration": "macbook::migration",
		"macbook/new_user": "macbook::new to mac",
		"macbook/service": "macbook::hardware service",
		"macbook/topics": "macbook::featured topics",
		"macbook/wifi": "macbook::wi-fi",
		"macbookair": "macbook air",
		"macbookair/accessories": "macbook air::accessories",
		"macbookair/applications": "macbook air::applications",
		"macbookair/batteries_power": "macbook air::batteries and power",
		"macbookair/bootcamp": "macbook air::boot camp",
		"macbookair/contact": "macbook air::contact",
		"macbookair/downloads": "macbook air::downloads",
		"macbookair/mail": "macbook air::mail",
		"macbookair/migration": "macbook air::migration",
		"macbookair/new_user": "macbook air::new to mac",
		"macbookair/service": "macbook air::hardware service",
		"macbookair/topics": "macbook air::featured topics",
		"macbookair/wifi": "macbook air::wi-fi",
		"macbookpro": "macbook pro",
		"macbookpro/accessories": "macbook pro::accessories",
		"macbookpro/applications": "macbook pro::applications",
		"macbookpro/batteries_power": "macbook pro::batteries and power",
		"macbookpro/bootcamp": "macbook pro::boot camp",
		"macbookpro/contact": "macbook pro::contact",
		"macbookpro/downloads": "macbook pro::downloads",
		"macbookpro/mail": "macbook pro::mail",
		"macbookpro/migration": "macbook pro::migration",
		"macbookpro/new_user": "macbook pro::new to mac",
		"macbookpro/service": "macbook pro::hardware service",
		"macbookpro/topics": "macbook pro::featured topics",
		"macbookpro/wifi": "macbook pro::wi-fi",
		"macmini": "mac mini",
		"macmini/accessories": "mac mini::accessories",
		"macmini/applications": "mac mini::applications",
		"macmini/bootcamp": "mac mini::boot camp",
		"macmini/contact": "mac mini::contact support",
		"macmini/downloads": "mac mini::recent software updates",
		"macmini/power": "mac mini::power and memory",
		"macmini/mail": "mac mini::mail",
		"macmini/migration": "mac mini::moving files to a new mac",
		"macmini/new_user": "mac mini::new to mac",
		"macmini/topics": "mac mini::featured topics",
		"macmini/wifi": "mac mini::wi-fi",
		"macos9": "mac os 9",
		"macosx/mailassistant": "mac os x::mail setup assistant",
		"macosxleopardserver/advancetopics": "mac os x server 10.5::advanced topics",
		"macosxleopardserver/filesharing": "mac os x server 10.5::file sharing",
		"macosxleopardserver/icalserver": "mac os x server 10.5::ical server",
		"macosxleopardserver/ichatserver": "mac os x server 10.5::ichat server",
		"macosxleopardserver": "mac os x server 10.5",
		"macosxleopardserver/install": "mac os x server 10.5::install",
		"macosxleopardserver/mailservices": "mac os x server 10.5::mail services",
		"macosxleopardserver/networkingvpn": "mac os x server 10.5::networking vpn",
		"macosxleopardserver/opendirectory": "mac os x server 10.5::open directory",
		"macosxleopardserver/podcastproducer": "mac os x server 10.5::podcast producer",
		"macosxleopardserver/webservices": "mac os x server 10.5::web services",
		"macosxtigerserver/additionaltopics": "mac os x server 10.4::additional topics",
		"macosxtigerserver/fileservices": "mac os x server 10.4::file services",
		"macosxtigerserver": "mac os x server 10.4",
		"macosxtigerserver/mailservice": "mac os x server 10.4::mail service",
		"macosxtigerserver/networkservices": "mac os x server 10.4::network service",
		"macosxtigerserver/opendirectory": "mac os x server 10.4::open directory",
		"macosxtigerserver/printservice": "mac os x server 10.4::print service",
		"macosxtigerserver/softwareupdate": "mac os x server 10.4::software update",
		"macosxtigerserver/webtechnologies": "mac os x server 10.4::web technologies",
		"macosxtigerserver/windowsservices": "mac os x server 10.4::windows services",
		"macpro": "mac pro",
		"macpro/accessories": "mac pro::accessories",
		"macpro/applications": "mac pro::applications",
		"macpro/bootcamp": "mac pro::boot camp",
		"macpro/contact": "mac pro::contact support",
		"macpro/downloads": "mac pro::recent software updates",
		"macpro/displays_storage": "mac pro::displays and storage",
		"macpro/mail": "mac pro::mail",
		"macpro/migration": "mac pro::moving files to a new mac",
		"macpro/new_user": "mac pro::new to mac",
		"macpro/topics": "mac pro::featured topics",
		"macpro/wifi": "mac pro::wi-fi",
		"mainstage": "mainstage",
		"mobileme": "mobileme",
		"mobileme/move": "mobileme::move to icloud",
		"mobileme/trial": "mobileme::trial",
		"mobileme/box-inquiries": "mobileme::cancelation request::redirect",
		"mobileme/box-inquiries/1/thankyou.html": "mobileme::cancelation acknowledgement 1::redirect",
		"mobileme/box-inquiries/2/thankyou.html": "mobileme::cancelation acknowledgement 2::redirect",
		"mobileme/cancel": "mobileme::cancelation request",
		"mobileme/cancel/1/thankyou.html": "mobileme::cancelation acknowledgement 1",
		"mobileme/cancel/2/thankyou.html": "mobileme::cancelation acknowledgement 2",
		"mobileme/code-refund": "mobileme::unused code refund request",
		"mobileme/code-refund/1/thankyou.html": "mobileme::unused code refund acknowledgement 1",
		"mobileme/code-refund/2/thankyou.html": "mobileme::unused code refund acknowledgement 2",
		"mobileme/code-refund/3/thankyou.html": "mobileme::unused code refund acknowledgement 3",
		"motion": "motion",
		"nikeplus": "ipod accessories::nikeplus",
		"numbers": "numbers",
		"pages": "pages",
		"panther": "mac os x 10.3",
		"photoservices/account": "photo services::account",
		"photoservices/cancel": "photo services::cancel",
		"photoservices/discounts": "photo services::discounts",
		"photoservices/gifts": "photo services::gifts",
		"photoservices": "photo services",
		"photoservices/orderstatus": "photo services::order status",
		"photoservices/returns": "photo services::returns",
		"photoservices/shipping": "photo services::shipping",
		"photoservices/terms": "photo services::terms",
		"photoservices/preparation_tips": "photo services::preparation tips",
		"photoservices/ordering_options": "photo services::ordering options",
		"photoservices/product_specs": "photo services::product line details",
		"photoservices/product_troubleshooting": "photo services::product troubleshooting",
		"photoservices/account_troubleshooting": "photo services::account troubleshooting",
		"photoservices/shipping_prices": "photo services::shipping prices",
		"photoservices/billing_inquiries": "photo services::billing inquiries",
		"photoservices/payment_options": "photo services::payment options",
		"photoservices/contact_us": "photo services::contact us",
		"powerbook": "powerbook g4",
		"powerbookg3": "powerbook g3",
		"powermac/g3": "power mac g3",
		"powermac/g4": "power mac g4",
		"powermac": "power mac g5",
		"proapps/serialnumbers": "pro apps::serial numbers",
		"quicktime": "quicktime",
		"remotedesktop": "remote desktop",
		"safari": "safari",
		"shake": "shake",
		"snowleopard": "mac os x 10.6",
		"snowleopardserver": "mac os x server 10.6",
		"software": "software",
		"soundtrack": "soundtrack",
		"soundtrackpro": "soundtrack pro",
		"tiger/3rdparty": "mac os x 10.4::third-party",
		"tiger/accounts": "mac os x 10.4::accounts",
		"tiger/addressbook": "mac os x 10.4::address book",
		"tiger/classic": "mac os x 10.4::classic",
		"tiger/features": "mac os x 10.4::features",
		"tiger": "mac os x 10.4",
		"tiger/install": "mac os x 10.4::installing",
		"tiger/internet": "mac os x 10.4::internet",
		"tiger/mail": "mac os x 10.4::mail",
		"tiger/network": "mac os x 10.4::network",
		"tiger/printing": "mac os x 10.4::printing",
		"waveburner": "waveburner",
		"webobjects": "webobjects",
		"xsan": "xsan",
		"xserve": "xserve",
		"xserveraid": "xserve raid"
	},
	
	"ta": {
		"ipad/assistant": "ipad",
		"ipad/assistant/mail": "ipad::mail",
		"ipad/assistant/itunes": "ipad::itunes",
		"ipad/assistant/applications": "ipad::applications",
		"ipad/assistant/wifi": "ipad::wifi",
		"ipad/assistant/airprint": "ipad::airprint",
		"iphone/assistant": "iphone",
		"iphone/assistant/airprint": "iphone::airprint",
		"iphone/assistant/application": "iphone::application",
		"iphone/assistant/calls": "iphone::calls",
		"iphone/assistant/itunes": "iphone::itunes",
		"iphone/assistant/mail": "iphone::mail",
		"iphone/assistant/notrecognized": "iphone::notrecognized::redirect",
		"iphone/assistant/phone": "iphone::phone",
		"iphone/assistant/receivemail": "iphone::receivemail",
		"iphone/assistant/restore": "iphone::restore",
		"iphone/assistant/sendmail": "iphone::sendmail",
		"iphone/assistant/voicemail": "iphone::voicemail",
		"iphone/assistant/wifi": "iphone::wifi",
		"iphone/chit/assistant": "ch-it::iphone",
		"iphone/chit/assistant/airprint": "ch-it::iphone::airprint",
		"iphone/chit/assistant/application": "ch-it::iphone::application",
		"iphone/chit/assistant/calls": "ch-it::iphone::calls",
		"iphone/chit/assistant/itunes": "ch-it::iphone::itunes",
		"iphone/chit/assistant/mail": "ch-it::iphone::mail",
		"iphone/chit/assistant/phone": "ch-it::iphone::phone",
		"iphone/chit/assistant/restore": "ch-it::iphone::restore",
		"iphone/chit/assistant/voicemail": "ch-it::iphone::voicemail",
		"iphone/chit/assistant/wifi": "ch-it::iphone::wifi",
		"iphone/troubleshooting/calls": "iphone::calls::redirect",
		"iphone/troubleshooting/itunes": "iphone::itunes::redirect",
		"iphone/troubleshooting/mail": "iphone::mail::redirect",
		"iphone/troubleshooting/phone": "iphone::phone::redirect",
		"ipodtouch/assistant": "ipod::ipod touch",
		"ipodtouch/assistant/application": "ipod::ipod touch::application",
		"ipodtouch/assistant/ipodtouch": "ipod::ipod touch",
		"ipodtouch/assistant/itunes": "ipod::ipod touch::itunes",
		"ipodtouch/assistant/receivemail": "ipod::ipod touch::mail",
		"ipodtouch/assistant/restore": "ipod::ipod touch::restore",
		"ipodtouch/assistant/sendmail": "ipod::ipod touch::mail",
		"ipodtouch/assistant/wifi": "ipod::ipod touch::wifi",
		"ipodtouch/troubleshooting": "ipod::ipod touch",
		"ipodtouch/troubleshooting/ipodtouch": "ipod::ipod touch",
		"ipodtouch/troubleshooting/itunes": "ipod::ipod touch::itunes",
		"ipodtouch/troubleshooting/mail": "ipod::ipod touch::mail",
		"ipod/five_rs": "ipod",
		"ipod/five_rs/classic": "ipod::ipod classic",
		"ipod/five_rs/ipod": "ipod::ipod family",
		"ipod/five_rs/ipod5gen": "ipod::ipod 5th gen",
		"ipod/five_rs/mini": "ipod::ipod mini",
		"ipod/five_rs/nano": "ipod::ipod nano",
		"ipod/five_rs/nano2gen": "ipod::ipod nano 2nd gen",
		"ipod/five_rs/nano3gen": "ipod::ipod nano 3rd gen",
		"ipod/five_rs/nano4gen": "ipod::ipod nano 4th gen",
		"ipod/five_rs/photo": "ipod::ipod photo",
		"ipod/five_rs/shuffle": "ipod::ipod shuffle",
		"ipod/five_rs/shuffle2gen": "ipod::ipod shuffle 2nd gen",
		"ipod/five_rs/shuffle3gen": "ipod::ipod shuffle 3rd gen",
		"ipod/five_rs/wheel": "ipod::ipod w/click wheel"
	},
	
	"faq": {
		"airport/service": "airport::service",
		"emac/service": "emac::service",
		"ibook/service": "ibook::service",
		"imac/service": "imac::service",
		"ipad/service": "ipad::service",
		"ipad/service/battery": "ipad::battery replacement",
		"ipad/service/exchange": "ipad::advance replacement",
		"ipad/service/faq": "ipad::service faq",
		"iphone/service/battery": "iphone::battery replacement",
		"iphone/service/exchange": "iphone::replacement service",
		"iphone/service/faq": "iphone::service",
		"ipod/service/faq": "ipod::service",
		"ipod/service/battery": "ipod::battery replacement",
		"ipodhifi/service/faq": "ipod::ipod hi-fi::service",
		"macbook/service": "macbook::service",
		"macbookair/service": "macbook air::service",
		"macbookair/service/battery": "macbook air::battery replacement",
		"macbookpro/service": "macbook pro::service",
		"macbookpro/service/battery": "macbook pro::battery replacement",
		"macmini/service": "mac mini::service",
		"nikeplus/service/faq": "ipod::nike plus::service",
		"powerbook/service": "powerbook g4::service",
		"powerbookg3/service": "powerbook g3::service",
		"powermac/service": "power mac::service",
		"xserve/service": "xserve::service"
	},
	
	"qp": {
		"imac-harddrive": "replacementprogram::imac 1tb seagate hard drive replacement::program page",
		"macbook-bottomcase": "repair extension::macbook bottom case replacement::program page",
		"usbadapter/exchangeprogram": "adapter exchange::iphone usb adapter",
		"validation": "mountain lion::imessage registration"
	},
	
	"price": {
		"ipod/service/price": "ipod::repair + battery replacement"
	},
	
	"survey": {
		"survey/applecareweb": "applecareweb",
		"survey/accs": "",
		"survey/accs/thankyou": ""
	},
	
	"tsp": {
		"homesharing": "home sharing",
		"homesharing/getstarted": "home sharing::get started",
		"homesharing/howto": "home sharing::how to",
		"homesharing/troubleshooting": "home sharing::troubleshooting"
	}

};

SCReporting.init();